---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfje/java-buildpack-dependency-builder
    tag: latest
    username: ((docker-username))
    password: ((docker-password))

inputs:
- name: java-buildpack-dependency-builder
- name: tomee-resource-configuration-archives

outputs:
- name: repository

run:
  path: java-buildpack-dependency-builder/tomee-resource-configuration.sh
