---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

inputs:
- name: java-buildpack-dependency-builder

outputs:
- name: artifactory-resource-docker-image
- name: http-resource-docker-image
- name: jprofiler-resource-docker-image
- name: maven-resource-docker-image
- name: pivotal-network-resource-docker-image
- name: tomcat-resource-docker-image
- name: wildfly-resource-docker-image
- name: your-kit-resource-docker-image

run:
  path: java-buildpack-dependency-builder/resources/ci/build.sh
